services:
  ratings:
    build: ./ratings/
    image: ghcr.io/piyanatnine/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - ./ratings/databases:/docker-entrypoint-initdb.d
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  details:
    build: ./details/
    image: ghcr.io/piyanatnine/bookinfo-details:dev
    ports:
      - "8081:9080"
  reviews:
    build: ./reviews/
    image: ghcr.io/piyanatnine/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      ENABLE_RATINGS: "true"
      RATINGS_SERVICE: http://ratings:8080
  productpage:
    build: ./productpage/
    image: ghcr.io/piyanatnine/bookinfo-productpage:dev
    ports:
      - "8083:9080"
    environment:
      REVIEWS_HOSTNAME: http://reviews:9080
      RATINGS_HOSTNAME: http://ratings:8080
      DETAILS_HOSTNAME: http://details:9080